### ISSUE TITLE
Humidity

### ISSUE THREAD

**Issue by Phreak87** [Mywk/FlipperTemperatureSensor#1]
Can you please implent a calculation under humidity with the absolute g/m3 value of water. This would be a great value to know in some scenarios

**Comment by Mywk** [comment]
You mean absolute humidity? Sure, just implemented it but want to test it before pushing.
I lent my Flipper but I'll test and upload it as soon as I have it back (two or three days).

## For those who want to know how the calculation works:

$A = C * \frac{P}{K}$

A 		-	Absolute Humidity
C		-	Constant of 2.16679 gK/J
P		-	Vapour pressure in Pa
K		-	Temperature in Kelvin

P is calculated with (S * Humidity / 100).
S		-	Saturation vapor pressure

To calculate PWS please refer to IAPWS IF-97, it's a bit too much to explain right now.
QND TLDR, the calculation can be done as follows:

$S = 6.11 * 10 ^ \frac{7.5 * °C}{237.3 + °C} $

To convert °C to Kelvin:

$273.15 + °C$

Note: hPa – Hectopascal Pressure Unit

----

Example with 22°C and relative humidity of 50%:

First we calculate S:

$S = 6.11 * 10 ^ \frac{7.5 * 22}{237.3 + 22}$

Then Pw:

$P = S * 50/100 \approx 13.22 hPa = 1322 Pa$

Let's calculate K (temperature in Kelvin)

$K = 273.15+22 = 295.15$

And we have everything we need for the the absolute humidity:

$A = 2.16679 * \frac{1322}{295.15} = 9.71 g/m3$

For 22°C, with a humidity of 50%, the absolute humidity is **9.71 g/m3**

**Comment by Mywk** [comment]
You mean absolute humidity? Sure, just implemented it but want to test it before pushing.
I lent my Flipper but I'll test and upload it as soon as I have it back (two or three days).

## For those who want to know how the calculation works:

$A = C * \frac{P}{K}$

A 		-	Absolute Humidity
C		-	Constant of 2.16679 gK/J
P		-	Vapour pressure in Pa
K		-	Temperature in Kelvin

P is calculated with (S * Humidity / 100).
S		-	Saturation vapor pressure

To calculate S please refer to IAPWS IF-97, it's a bit too much to explain right now.
QND TLDR, the calculation can be done as follows:

$S = 6.11 * 10 ^ \frac{7.5 * °C}{237.3 + °C} $

To convert °C to Kelvin:

$273.15 + °C$

Note: hPa – Hectopascal Pressure Unit

----

Example with 22°C and relative humidity of 50%:

First we calculate S:

$S = 6.11 * 10 ^ \frac{7.5 * 22}{237.3 + 22}$

Then Pw:

$P = S * 50/100 \approx 13.22 hPa = 1322 Pa$

Let's calculate K (temperature in Kelvin):

$K = 273.15+22 = 295.15$

And we have everything we need for the the absolute humidity:

$A = 2.16679 * \frac{1322}{295.15} = 9.71 g/m3$

For 22°C, with a humidity of 50%, the absolute humidity is **9.71 g/m3**

**Comment by Mywk** [comment]
Tested and uploaded. Check for the latest compiled version [here](https://github.com/Mywk/FlipperTemperatureSensor/releases).
